MERGE INTO [dbo].[COURSE_OPTION_CLUSTER_SUB_PROG] AS TARGET
USING (VALUES
('o1','c06','s17','p005','KSP 477','C'),
('o2','c06','s17','p005','KSP 476','C')
)
AS SOURCE ([OPTION_ID], [CLUSTER_ID], [SUB_PROG_ID], [PROG_NUM], [COURSE_NUM], [MIN_GRADE])
ON TARGET.[OPTION_ID] = SOURCE.[OPTION_ID]
	AND TARGET.[CLUSTER_ID] = SOURCE.[CLUSTER_ID]
	AND TARGET.[SUB_PROG_ID] = SOURCE.[SUB_PROG_ID]
	AND TARGET.[PROG_NUM] = SOURCE.[PROG_NUM]
	AND TARGET.[COURSE_NUM] = SOURCE.[COURSE_NUM]

--INSERT WHEN NOT MATCHED
WHEN NOT MATCHED BY TARGET THEN
INSERT ([OPTION_ID], [CLUSTER_ID], [SUB_PROG_ID], [PROG_NUM], [COURSE_NUM], [MIN_GRADE])
VALUES (SOURCE.[OPTION_ID], SOURCE.[CLUSTER_ID], SOURCE.[SUB_PROG_ID], SOURCE.[PROG_NUM], SOURCE.[COURSE_NUM], SOURCE.[MIN_GRADE]);

GO