MERGE INTO [dbo].[COURSE_OFFERING] AS TARGET
USING (VALUES
	(1, 'SPRING'),
	(2, 'SUMMER'),
	(3, 'FALL'),
	(4, 'FALL, SPRING'),
	(5, 'SPRING, SUMMER'),
	(6, 'FALL, SUMMER'),
	(7, 'FALL, SPRING, SUMMER'),
	(8, 'VARIABLE'),
	(9, 'ON-DEMAND')
)
AS SOURCE ([COURSE_OFFERED], [DESCRIPTIONS])
ON TARGET.[COURSE_OFFERED] = SOURCE.[COURSE_OFFERED]

--Update matched rows
WHEN MATCHED THEN
UPDATE SET [DESCRIPTIONS] = SOURCE.[DESCRIPTIONS]

--INSERT WHEN NOT MATCHED
WHEN NOT MATCHED BY TARGET THEN
INSERT ([COURSE_OFFERED], [DESCRIPTIONS])
VALUES (SOURCE.[COURSE_OFFERED], SOURCE.[COURSE_OFFERED]);

GO