MERGE INTO [dbo].[GOAL_AREA] AS TARGET
USING (VALUES
('1A','COMMUNICATION - ENGLISH COMPOSITION',3,3,''),
('1B','COMMUNICATION - SPEECH AND ORAL REASONING',3,3,''),
('1C','COMMUNICATION - WRITING INTENSIVE',6,6,'REQUIRES TWO COURSES FROM DIFFERENT DISCIPLINES'),
('2','CRITICAL THINKING',0,2,'REQUIRES COMPLETION OF THE REST OF THE GEN ED PROGRAM OR ONE COURSE'),
('3','NATURAL SCIENCE',6,6,'REQUIRES TWO COURSES FROM DIFFERENT DISCIPLINES, AT LEAST ONE COURSE MUST HAVE A LABORATORY'),
('4','MATHEMATICAL/LOGICAL REASONING',3,3,''),
('5','HISTORY AND THE SOCIAL AND BEHAVIORAL SCIENCES',6,6,'REQUIRES TWO COURSES FROM DIFFERENT DISCIPLINES'),
('6','HUMANITIES AND THE ARTS',6,6,'REQUIRES TWO COURSES FROM DIFFERENT DISCIPLINES'),
('7','HUMAN DIVERSITY',3,3,''),
('8','GLOBAL PERSPECTIVE',3,3,''),
('9','ETHICAL AND CIVIC RESPONSIBILITY',3,3,''),
('10','PEOPLE AND THE ENVIRONMENT',3,3,''),
('11','PERFORMANCE AND PARTICIPATION',2,3,'REQUIRES 2-3 CREDITS'),
('12','FIRST YEAR EXPERIENCE',0,1,'REQUIRES 0-1 CREDITS'),
('13','INFORMATION TECHNOLOGY',0,2,'REQUIRES 0-2 CREDITS')
)
AS SOURCE ([GOAL_AREA_ID], [GOAL_AREA_NAME], [MAX_CREDIT_HOURS_REQ], [MIN_CREDIT_HOURS_REQ], [SPECIAL_NOTES])
ON TARGET.[GOAL_AREA_ID] = SOURCE.[GOAL_AREA_ID]


--INSERT WHEN NOT MATCHED
WHEN NOT MATCHED BY TARGET THEN
INSERT ([GOAL_AREA_ID], [GOAL_AREA_NAME], [MAX_CREDIT_HOURS_REQ], [MIN_CREDIT_HOURS_REQ], [SPECIAL_NOTES])
VALUES (SOURCE.[GOAL_AREA_ID], SOURCE.[GOAL_AREA_NAME], SOURCE.[MAX_CREDIT_HOURS_REQ], SOURCE.[MIN_CREDIT_HOURS_REQ], SOURCE.[SPECIAL_NOTES]);

GO