IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'DEPARTMENT_INDEX' AND object_id = OBJECT_ID('DEPARTMENT'))
BEGIN
    CREATE INDEX DEPARTMENT_INDEX ON DEPARTMENT (DEPT_NAME);
END;

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'COURSE_INDEX' AND object_id = OBJECT_ID('COURSE'))
BEGIN
    CREATE INDEX COURSE_INDEX ON COURSE (COURSE_NUM, COURSE_NAME);
END;

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'COMPANY_INDEX' AND object_id = OBJECT_ID('COMPANY'))
BEGIN
    CREATE INDEX COMPANY_INDEX ON COMPANY (COMP_NAME);
END;

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'PROGRAM_INDEX' AND object_id = OBJECT_ID('PROGRAM'))
BEGIN
    CREATE INDEX PROGRAM_INDEX ON PROGRAM (PROG_NUM, PROG_NAME, DEPT_NUM);
END;

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'TEACHER_INDEX' AND object_id = OBJECT_ID('TEACHER'))
BEGIN
    CREATE INDEX TEACHER_INDEX ON TEACHER (LNAME, TEACHER_NUM, DEPT_NUM);
END;

IF NOT EXISTS(SELECT * FROM sys.indexes WHERE name = 'CERTIFICATION_INDEX' AND object_id = OBJECT_ID('CERTIFICATION'))
BEGIN
    CREATE INDEX CERTIFICATION_INDEX ON CERTIFICATION (CERTID, CATEGORY, DESCRIPTION);
END;

GO

--CREATE INDEX JOB_INDEX ON JOB (JNO, JOB_NAME);
--CREATE INDEX STUDENT_INDEX ON STUDENT (STUD_NUM, DEPT_NUM);