MERGE INTO [dbo].[OPTIONAL_CLUSTER_SUB_PROGRAM] AS TARGET
USING (VALUES
--Health and Physical Education--
('o1','c06','s17','p005','For 5-12 Majors',11),
('o2','c06','s17','p005','For K-12 Majors',11)
)
AS SOURCE ([OPTION_ID], [CLUSTER_ID], [SUB_PROG_ID], [PROG_NUM], [NAME], [CREDIT_HOURS])
ON TARGET.[OPTION_ID] = SOURCE.[OPTION_ID]
	AND TARGET.[CLUSTER_ID] = SOURCE.[CLUSTER_ID]
	AND TARGET.[SUB_PROG_ID] = SOURCE.[SUB_PROG_ID]
	AND TARGET.[PROG_NUM] = SOURCE.[PROG_NUM]

--INSERT WHEN NOT MATCHED
WHEN NOT MATCHED BY TARGET THEN
INSERT ([OPTION_ID], [CLUSTER_ID], [SUB_PROG_ID], [PROG_NUM], [NAME], [CREDIT_HOURS])
VALUES (SOURCE.[OPTION_ID], SOURCE.[CLUSTER_ID], SOURCE.[SUB_PROG_ID], SOURCE.[PROG_NUM], SOURCE.[NAME], SOURCE.[CREDIT_HOURS]);

GO