CREATE TABLE [dbo].[CERT](
STUD_NUM NVARCHAR(10) NOT NULL,
CERTID NVARCHAR (10) NOT NULL,
YEAR_OF_CERTIFICATION NVARCHAR (50),
CONSTRAINT CERT_STUDNUM_CERTID_PK PRIMARY KEY (STUD_NUM, CERTID),
CONSTRAINT CERT_STUD_NUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM),
CONSTRAINT CERT_CERTID_FK FOREIGN KEY (CERTID) REFERENCES CERTIFICATION(CERTID));