CREATE TABLE [dbo].[CLUSTER_SUB_PROGRAM] 
(	
CLUSTER_ID NVARCHAR(20) NOT NULL, 
SUB_PROG_ID NVARCHAR(20) NOT NULL, 
PROG_NUM NVARCHAR(10) NOT NULL,  
CREDIT_HOURS  NUMERIC(10,0) NOT NULL, 
NAME NVARCHAR(100), 
HAS_OPTIONS NUMERIC, 
CONSTRAINT CLUSTER_SUB_PROGRAM_PK PRIMARY KEY (CLUSTER_ID, SUB_PROG_ID, PROG_NUM), 
CONSTRAINT CLUSTER_SUB_PROGRAM_SUB_P_FK1 FOREIGN KEY (SUB_PROG_ID, PROG_NUM) REFERENCES 
SUB_PROGRAM (SUB_PROG_ID, PROG_NUM)
);