CREATE TABLE [dbo].[CONCURENT_COURSE](
COURSE_NUM NVARCHAR(20) NOT NULL,
CON_COURSE_NUM NVARCHAR(20) NOT NULL,
CONSTRAINT CONCURENT_COURSE_PK PRIMARY KEY (COURSE_NUM),
CONSTRAINT CONCURENT_COURSE_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM));