CREATE TABLE [dbo].[COURSE_CHG_HIST](
CHG_TYPE NVARCHAR(20) NOT NULL,
DATE_CHANGED DATE NOT NULL,
COURSE_NUM NVARCHAR(20) NOT NULL,
CHANGE_FROM VARCHAR(50) NOT NULL,
CHANGE_TO VARCHAR(20) NOT NULL,
CONSTRAINT COURSE_CHG_PK PRIMARY KEY (COURSE_NUM, DATE_CHANGED),
CONSTRAINT COURSE_CHG_HIST_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM));
