CREATE TABLE [dbo].[COURSE](
COURSE_NUM NVARCHAR(20) NOT NULL,
COURSE_NAME NVARCHAR(100),
DEPT_NUM NVARCHAR(10),
CREDIT_HRS NUMERIC(3,0),
COURSE_OFFERED NUMERIC(1,0),
CONSTRAINT COURSE_COURSE_NUM_PK PRIMARY KEY (COURSE_NUM),
CONSTRAINT COURSE_DEPT_NUM_FK FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT(DEPT_NUM),
CONSTRAINT COURSE_OFFERED_FK FOREIGN KEY (COURSE_OFFERED) REFERENCES COURSE_OFFERING(COURSE_OFFERED));