CREATE TABLE [dbo].[COURSE_CLUSTER_SUB_PROGRAM] 
(	
CLUSTER_ID NVARCHAR(20) NOT NULL, 
SUB_PROG_ID NVARCHAR(20) NOT NULL, 
PROG_NUM NVARCHAR(10) NOT NULL,  
COURSE_NUM  NVARCHAR(20) NOT NULL, 
MIN_GRADE NVARCHAR(10) NOT NULL, 
 CONSTRAINT COURSE_CLUSTER_SUB_PROGRAM_PK PRIMARY KEY (CLUSTER_ID, SUB_PROG_ID, PROG_NUM,COURSE_NUM), 
 CONSTRAINT COURSE_CLUSTER_SUB_PROGRAM_FK1 FOREIGN KEY (CLUSTER_ID,SUB_PROG_ID, PROG_NUM) 
 REFERENCES CLUSTER_SUB_PROGRAM (CLUSTER_ID,SUB_PROG_ID, PROG_NUM),
 CONSTRAINT COURSE_CLUSTER_SUB_PROGRAM_FK2 FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM));