CREATE TABLE COURSE_SUB_PROGRAM
(	
PROG_NUM NVARCHAR(10) NOT NULL, 
COURSE_NUM  NVARCHAR(20) NOT NULL,
SUB_PROG_ID NVARCHAR(20) NOT NULL,  
MIN_GRADE NVARCHAR(10) NOT NULL,

CONSTRAINT COURSE_SUB_PROGRAM_PK PRIMARY KEY (PROG_NUM,COURSE_NUM,SUB_PROG_ID),
CONSTRAINT COURSE_SUB_PROGRAM_FK1 FOREIGN KEY (SUB_PROG_ID, PROG_NUM) REFERENCES 
SUB_PROGRAM (SUB_PROG_ID, PROG_NUM),
CONSTRAINT COURSE_SUB_PROGRAM_FK2 FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM)
);
