CREATE TABLE [dbo].[COURSE_MULTI_CREDIT](
MAX_CH NUMERIC(3,0) NOT NULL,
MIN_CH NUMERIC(3,0) NOT NULL,
COURSE_NUM NVARCHAR(20) NOT NULL,
CONSTRAINT COURSE_MULTI_CRD_PK PRIMARY KEY (MAX_CH, MIN_CH, COURSE_NUM),
CONSTRAINT COURSE_MULTI_CRD_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM));
