CREATE TABLE [dbo].[DEPT_NAME_HIST](
DATE_CHANGED DATE NOT NULL,
DEPT_NUM NVARCHAR(10) NOT NULL,
NAME VARCHAR(50) NOT NULL,
CONSTRAINT DEPT_NAME_HIST_PK PRIMARY KEY (DATE_CHANGED, DEPT_NUM),
CONSTRAINT DEPT_NAME_HIST_FK FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT (DEPT_NUM));
