CREATE TABLE EMPLOYED(
STUD_NUM NVARCHAR(10) NOT NULL,
COMP_ID NVARCHAR(10) NOT NULL,
JNO NVARCHAR(10) NOT NULL,
CONSTRAINT EMPLOYED_PK PRIMARY KEY (STUD_NUM, COMP_ID, JNO),
CONSTRAINT EMPLOYED_STUDNUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM),
CONSTRAINT EMPLOYED_COMPID_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY(COMP_ID),
CONSTRAINT EMPLOYED_JNO_FK FOREIGN KEY (JNO) REFERENCES JOB(JNO));