CREATE TABLE [dbo].[ENROLLMENT](
ENROLL_ID NVARCHAR(30) NOT NULL,
STUD_NUM NVARCHAR(10),
YEAR NVARCHAR(10),
TERM NVARCHAR(10),
GRADE NVARCHAR(10),
TEACHER_NUM NVARCHAR(10),
COURSE_NUM NVARCHAR(20),
CONSTRAINT EMROLLMENT_PK PRIMARY KEY (ENROLL_ID),
CONSTRAINT ENROLLMENT_STUDNUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM),
CONSTRAINT ENROLLMENT_TEACHERNUM_FK FOREIGN KEY (TEACHER_NUM) REFERENCES TEACHER(TEACHER_NUM),
CONSTRAINT ENROLLMENT_COURSENUM_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE(COURSE_NUM));