CREATE TABLE [dbo].[GEN_ED_COURSE] (
COURSE_NUM	NVARCHAR(20)	NOT NULL,
GOAL_AREA_ID NVARCHAR(5) NOT NULL,
LABORATORY	NVARCHAR(1),
GOLD_CULTUR_DIVER	NVARCHAR(1),
PURPLE_CULTUR_DIVER	NVARCHAR(1),
CATALOG_YEAR NVARCHAR(20) NOT NULL,
CONSTRAINT GEN_ED_COUR_PK PRIMARY KEY (COURSE_NUM, GOAL_AREA_ID, CATALOG_YEAR),
CONSTRAINT GEN_ED_COUR_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE (COURSE_NUM),
CONSTRAINT GEN_ED_FK2 FOREIGN KEY (GOAL_AREA_ID) REFERENCES GOAL_AREA (GOAL_AREA_ID));
