CREATE TABLE [dbo].[GOAL_AREA] (
GOAL_AREA_ID	NVARCHAR(5)	NOT NULL,
GOAL_AREA_NAME	NVARCHAR(50),
MAX_CREDIT_HOURS_REQ	NUMERIC (2,0),
MIN_CREDIT_HOURS_REQ	NUMERIC (2,0),
SPECIAL_NOTES	NVARCHAR(2000),
CONSTRAINT GOAL_AREA_ID_PK PRIMARY KEY (GOAL_AREA_ID));
