CREATE TABLE [dbo].[INTERNSHIP](
STUD_NUM NVARCHAR(10) NOT NULL,	
COMP_ID NVARCHAR(10) NOT NULL,
JNO NVARCHAR(10) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE,
CREDITS NVARCHAR(10),
CONSTRAINT INTERNSHIP_PK PRIMARY KEY (STUD_NUM, COMP_ID, JNO, START_DATE),
CONSTRAINT INTERNSHIP_STUDNUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT(STUD_NUM),
CONSTRAINT INTERNSHIP_COMPID_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY (COMP_ID));