CREATE TABLE [dbo].[JOB_PROG] (
	JNO		NVARCHAR(10) NOT NULL,
	PROG_NUM 	NVARCHAR(10) NOT NULL,	
CONSTRAINT JOB_PROG_PK PRIMARY KEY (JNO, PROG_NUM),
CONSTRAINT JOB_PROG_PROG_NUM_FK FOREIGN KEY (PROG_NUM) REFERENCES PROGRAM,
CONSTRAINT JOB_PROG_JNO_FK FOREIGN KEY (JNO) REFERENCES JOB
);
