CREATE TABLE [dbo].[MISSING_COURSE] (
	STUD_NUM	NVARCHAR(10) NOT NULL,
	PROG_NUM 	NVARCHAR(10) NOT NULL,
	COURSE_NUM	NVARCHAR(20) NOT NULL,
	CATALOG_YEAR	NVARCHAR(11) NOT NULL,
	COURSE_TYPE	NVARCHAR(20) NOT NULL,
	REQ		CHAR(1)	NOT NULL,	
CONSTRAINT MISSING_COURSE_PK PRIMARY KEY (STUD_NUM,PROG_NUM,COURSE_NUM,CATALOG_YEAR),
CONSTRAINT MISSING_COURSE_FK FOREIGN KEY (PROG_NUM,STUD_NUM,CATALOG_YEAR) REFERENCES STUD_PROG,
CONSTRAINT MISSING_COURSE_COURSE_NUM_FK FOREIGN KEY (COURSE_NUM) REFERENCES COURSE
);
