CREATE TABLE [dbo].[PREREQUISITE] (
COURSE_NUM NVARCHAR(20),
OPTION_NUM INTEGER,
PRE_COURSE NVARCHAR(20),
GRADE_REQ NUMERIC(3,2),
CONSTRAINT PRE_C_O_P_PK PRIMARY KEY (COURSE_NUM, OPTION_NUM, PRE_COURSE),
CONSTRAINT PRE_COURSE_NO_FK FOREIGN KEY (COURSE_NUM)
	REFERENCES COURSE(COURSE_NUM),
CONSTRAINT PRE_PRE_COURSE_NO_FK FOREIGN KEY (PRE_COURSE)
	REFERENCES COURSE(COURSE_NUM));