CREATE TABLE [dbo].[PROGRAM]
(
	PROG_NUM NVARCHAR(10) NOT NULL,
	PROG_NAME NVARCHAR(50),
	DEPT_NUM NVARCHAR(10),
	TYPE NVARCHAR(20),
	CLASS NVARCHAR(50),
	TOTAL_CH NUMERIC(10),
	DESCRIPTION NVARCHAR(4000),
	CATALOG_YEAR NVARCHAR(20),
	MINOR_REQUIRED NVARCHAR(2000),
	CONSTRAINT PROGRAM_PROGNUM_PK PRIMARY KEY (PROG_NUM),
	CONSTRAINT PROGRAM_DEPTNUM_FK FOREIGN KEY (DEPT_NUM) REFERENCES	DEPARTMENT(DEPT_NUM)
)
