CREATE TABLE [dbo].[RETAKE_GEN_ED](
	STUD_NUM INTEGER,
	COURSE_NUM NVARCHAR(9),
	GEN_ED_COURSE NVARCHAR(9),
	[YEAR] INTEGER,
	TERM NVARCHAR(6),
	GRADE CHAR(1),
	YEAR_ENROLL INTEGER,
	TERM_ENROLL NVARCHAR(6));  