CREATE TABLE [dbo].[STUD_PROG] (
	PROG_NUM 	NVARCHAR(10) NOT NULL,
	STUD_NUM	NVARCHAR(10) NOT NULL,
	CATALOG_YEAR	NVARCHAR(11) NOT NULL,
	[STATUS]	NVARCHAR(20),
	STATUS_DATE	DATE,
	SPECIALIZATION NVARCHAR(20),	
CONSTRAINT STUD_PROG_PK PRIMARY KEY (STUD_NUM,PROG_NUM,CATALOG_YEAR),
CONSTRAINT STUD_PROG_PROG_NUM_FK FOREIGN KEY (PROG_NUM) REFERENCES PROGRAM,
CONSTRAINT STUD_PROG_COURSE_NUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT
);
