CREATE TABLE [dbo].[STUDENT_WORKED](
STUD_NUM NVARCHAR(10) NOT NULL,
CLASSIFICATION NVARCHAR(10) NOT NULL,
AVG_HOURS NVARCHAR(10),
CONSTRAINT SW_PK PRIMARY KEY (STUD_NUM, CLASSIFICATION),
CONSTRAINT SW_STUDNUM_FK FOREIGN KEY (STUD_NUM) REFERENCES STUDENT (STUD_NUM));
