CREATE TABLE [dbo].[TEACHER](
TEACHER_NUM NVARCHAR(10) NOT NULL,
DEPT_NUM NVARCHAR(10),
LNAME NVARCHAR(25),
FNAME NVARCHAR(25),
CONSTRAINT TEACHER_TEACHERNUM_PK PRIMARY KEY (TEACHER_NUM),
CONSTRAINT TEACHER_DEPTNUM_FK FOREIGN KEY (DEPT_NUM) REFERENCES DEPARTMENT (DEPT_NUM));
